### PR TITLE
Better readme

### PR DESCRIPTION
**Pull request by tafia**
Better description / examples / disclaimers

### CODE REVIEW

**Comment by tafia** [comment]
cc @brunoqc would you have time to comment on this? 
English is not my first language ...

[rendered](https://github.com/tafia/office/blob/adc64387154f870134047ca3ff7e87e819a37322/README.md)

**Comment by tafia** [comment]
Closes #20

**Comment by brunoqc** [comment]
English is not my first language either and you write pretty well so it's very possible that your English is better than mine :). The README seems fine.

I like the examples in the README but they could be a bit intimidating to functional programming noobs (like me) I wonder if it would be a good idea also add a really simple exemple like:
```rust
let mut excel = Excel::open("file.xlsx").unwrap();
let r = excel.worksheet_range("Sheet1").unwrap();
for row in r.rows() {
    println!("row={:?}, row[0]={:?}", row, row[0]);
}
```

It could be a nice copy/paste starting point.

**Comment by tafia** [comment]
Thanks!
Merging now

**Pull request merged**
