### PR TITLE
Support RichTextRun shared strings

### PR DESCRIPTION
**Pull request by brunoqc**
Note that I discard the style (font...). Maybe you want a DataType::RichText.

### CODE REVIEW

**Comment by brunoqc** [comment]
That's weird, I thought the PR would be mentioned in #9 automatically.

**Comment by tafia** [comment]
Awesome!
I don't necessarily want a new type, what you've done looks good to me.

One point though, I'd prefer having a `rich_buffer: Option<String>` to replace both the `String` and the flag. This feel more rustic to me and we pay for the `String` allocation only when needed.

**Comment by brunoqc** [comment]
I pushed a new commit using Option<String>.

> I'd prefer having a rich_buffer: Option<String> to replace both the String and the flag. This feel more rustic to me and we pay for the String allocation only when needed.

Yes it's better and I doesn't need to clone the string when I add it to the vector.

I also changed the unit test to ensure that rich_buffer is reset if there's more than one <si> with rich text.

**Comment by tafia** [comment]
Thanks for your time!

**Pull request merged**
