### PR TITLE
ignore formula and add DataType::Bool

### LINKED ISSUE #6: error "not v node" when the cell is a formula
formula: CONCAT("a", "b")

### PR DESCRIPTION
**Pull request by tafia**
closes #6

### CODE REVIEW

**Comment by tafia** [comment]
This is a breaking change because of new `DataType::Bool` variant

**Comment by tafia** [comment]
!brunocq, let me know if it suits you

**Comment by brunoqc** [comment]
I'll test right now.

**Comment by brunoqc** [comment]
It works 👍

**Comment by tafia** [comment]
Nice!
Thanks again for reporting all these errors. My use case was very simplistic and I didn't spend the time I should on this. Sorry for that and thanks for making this evolve!

**Comment by brunoqc** [comment]
> My use case was very simplistic and I didn't spend the time I should on this. Sorry for that

No worries. Thanks for the quick updates. I'll test the other issue when I'll be at work.

**Pull request merged**
